### ISSUE TITLE
Compiled Release?

### ISSUE THREAD

**Issue by Dannii-Darkness** [AzeTheGreat/Hotkeys#1]
Any chance you might be able to do a release for this?

Unfortunately, I don't know anything about coding and compiling otherwise I would do it myself. From what I read online I don't even know if I could do it without compiling instructions anyway.

I'd like to be able to have shortcut keys for an item/unit's info-tab and all the colonist tabs (Bio, Needs, etc.) among other things. Drives me nuts having to mouse all over the place too! I'm really surprised to find this hasn't attracted more interest. Anyone would think RimWorld was a console release (aka "what's a hotkey").

Anyway, given that it doesn't appear a whole load of people would end up benefiting from a release, I understand if it's not something you want to put the work into, but many thanks if you do manage to find the time.

Dannii

**Comment by AzeTheGreat** [comment]
Hey @Dannii-Darkness , sorry I didn't see this earlier, I'm new to github and don't really use it much...

I'm actually putting together a release right now, but you can also just subscribe on the steam workshop here: https://steamcommunity.com/sharedfiles/filedetails/?id=1546677282

I will consider adding shortcuts for the colonist tabs - I don't think it would be too much work.

**Comment by Dannii-Darkness** [comment]
Thankyou for the release much appreciated!!

BTW, the about/assemblies/defs folders in the current release.zip are saved to the zip file's root directory, meaning these folders end up extracting to the RimWorld mod directory unless you specifically create the Hotkeys folder and unzip the release there.

I'm only mentioning this because you said that you are new to Github, and the release format, from what I've seen, is that these mod folders are saved inside a mod-named folder (ie. Hotkeys), I assume for ease of installation - if that makes sense? Not that I think this will stump anyone downloading from here, but perhaps something to keep in mind for future releases and projects? :) Once again, thanks.

**Comment by AzeTheGreat** [comment]
You know...I've always used 7zip to extract to a new folder, and the superfluous folder always annoyed me.  Now I get the point...I'll fix the formatting on the next release I do, thanks!
