### ISSUE TITLE
Thanks for the mod! And a question.

### ISSUE THREAD

**Issue by ww9** [AzeTheGreat/Hotkeys#2]
Just wanted to say thank you for making the mod and sharing the source-code.

Do you think keybindings for Architect menu is a good idea?

![image](https://user-images.githubusercontent.com/27555162/51481671-2b839900-1d73-11e9-9bd8-8171a445a114.png)

I just noticed that right-clicking anywhere opens the Architect menu and it would be awesome to activate individual items with keybindings. I loathe having to move cursor to that menu.

**Comment by AzeTheGreat** [comment]
Hey there, not sure why I wasn't notified of this issue, but I just now saw it...

The mod should currently support keybindings for the architect menu.

Make sure Architect Hotkeys are enabled under the mod settings.  You should then be able to assign keys to any of the tabs in the standard hotkey menu (under the "Architect Hotkeys" category).  If these are not present or not working, or if I've misunderstood what you're talking about, please let me know.
