### ISSUE TITLE
Missing mod settings 

### ISSUE THREAD

**Issue by matshou** [AzeTheGreat/Hotkeys#3]
Game version: `1.2.2753`
Mod version: `1.4.3` (latest)
Mods running: `None`

I've just downloaded your mod and wanted to try out setting a few hotkeys but after watching the demo and trying to figure out how to exactly do that I find that I am missing some mod settings as shown in your demo video on Youtube.

I am running no mods (pure vanilla) and I've tested this by running a new colony.

![2020-10-27_125137](https://user-images.githubusercontent.com/16436920/97298247-7210fc00-1853-11eb-85d4-8a3594c864e8.png)

If you could help shed some light on this issue I would be most appreciative.
Thank you in advance for helping resolve this issue!

**Comment by AzeTheGreat** [comment]
The demo was from a much older version of the mod that used a totally different UI (and was significantly less flexible).  I've updated the demo video, which you can see here: https://youtu.be/-J79sizC9es

The Steam Workshop description contains more information on how to use the mod, please let me know if you get stuck or run into any issues after reading that, thanks.
